#!/bin/bash

# CircleOS Live Build Configuration

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --linux-flavours amd64 \
    --bootappend-live "boot=live components quiet splash" \
    --bootloaders grub-efi \
    --binary-images iso-hybrid \
    --iso-application "CircleOS" \
    --iso-publisher "CircleOS Project" \
    --iso-volume "CircleOS 1.0.0" \
    --image-name "circleos-1.0.0-amd64" \
    --debian-installer false \
    --apt-recommends true \
    --apt-indices false \
    --checksums sha256 \
    --clean \
    circleos-live noauto --mode debian --distribution bookworm --archive-areas main contrib non-free non-free-firmware --architectures amd64 --linux-flavours amd64 --bootappend-live boot=live components quiet splash --bootloaders grub-efi --binary-images iso-hybrid --iso-application CircleOS --iso-publisher CircleOS Project --iso-volume CircleOS 1.0.0 --image-name circleos-1.0.0-amd64 --debian-installer false --apt-recommends true --apt-indices false --checksums sha256 --clean circleos-live circleos-live "${@}"
